### ISSUE TITLE
HTML input is not being escaped

### ISSUE THREAD

**Issue by Derpzz** [HAWK-Digital-Environments/HAWKI#22]
While code that has been created by ChatGPT is successfully escaped, user input is not escaped. 

<img width="1728" alt="grafik" src="https://github.com/HAWK-Digital-Environments/HAWKI/assets/54187947/0cdab8f5-a264-4b77-ad31-6a8c3c0cc4e4">

**Comment by MixColumns** [comment]
has this been fixed yet?
