### ISSUE TITLE
LaTex renderer

### ISSUE THREAD

**Issue by KBorm** [HAWK-Digital-Environments/HAWKI#29]
One of our employees noticed that responses containing LaTex are not rendered as expected. 
He states that ChatGPT is rendereing LaTex properly.

This feature should/could be added.

**Comment by Ariansdf** [comment]
Hi @KBorm. Thank you for raising the issue.
LaTex renderer is added in the upcoming update.
The render is of course for inline math formulas and not LaTex Documents generated by chatGPT.
