### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by graphuser-art** [HAWK-Digital-Environments/HAWKI#31]
Hey, 

is it possible to add a chat history like in the Interface provided by ChatGPT?

**Comment by Ariansdf** [comment]
Hi @graphuser-art  
at the moment we don't save any information on our database, therefore it's not possible to have a history on the current version of HAWKI.
It's of course possible to connect your own database and pass the data from interface.php after each message is sent. But for security reasons, we haven't implemented it.

**Comment by MixColumns** [comment]
The Web Storage API https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API allows to save up to 5 MiB of local storage, and 5 MiB of session storage per origin. I think this might be an idea to store chat histories. It would allow users to keep the chat history localy within their browser files without them being stored anywhere.
