### ISSUE TITLE
Edit Button

### ISSUE THREAD

**Issue by StenSeegel** [HAWK-Digital-Environments/HAWKI#33]
![Bildschirmfoto 2024-02-22 um 13 07 59](https://github.com/HAWK-Digital-Environments/HAWKI/assets/121229940/3b1f80a4-0726-45fd-b9f2-b020f1c2bd18)
![Bildschirmfoto 2024-02-22 um 13 08 23](https://github.com/HAWK-Digital-Environments/HAWKI/assets/121229940/b89adb49-9e48-4930-9d36-46ee28c5b6c6)
![Bildschirmfoto 2024-02-22 um 13 13 17](https://github.com/HAWK-Digital-Environments/HAWKI/assets/121229940/81f17c41-b84d-4224-ab9e-5ddcf854538f)

Please add the ability to edit user content and create multiple forks in conversations. Revising the user input is a useful method for generating better model output. In this way, it's possible to create more meaningful conversations that contain only high quality model output. Errors generated by the model will most often corrupt the context and cause errors to creep into subsequent model output. It's important for good model output that the user is able to control the entire content of the context.

**Comment by Ariansdf** [comment]
Hey @Sten
you already know...
I'm going to close this one too.
