### ISSUE TITLE
Testuser does not work as stated in the readme

### ISSUE THREAD

**Issue by sehomer** [HAWK-Digital-Environments/HAWKI#34]
Hi,

the readme states that you have to configure 'testuser=true' and to use "superlangespasswort123".

The actual code commented out the test-login, stating to activate it if needed. The login php uses anonther password than stated in the readme.

Best regards
sehomer

**Comment by davidlohner** [comment]
Workaround:

edit the login.php, so the section for the testuser is not a comment. There you can change username and password for the testuser.

**Comment by MixColumns** [comment]
Seems like a good fix

**Comment by Ariansdf** [comment]
Hey everyone,
I've changed the code in the last update a little. if you want to include the test user just add the username and password in the .env file. Or you can leave the value empty or comment out the variables to disable it.
