### ISSUE TITLE
Separate out files for deployment by using a different directory

### ISSUE THREAD

**Issue by nicoroeser** [HAWK-Digital-Environments/HAWKI#36]
Currently the `.htaccess` file aims to prevent accesses to files not intended for HAWKI users. It does not contain an entry for `composer_install.sh`, for example.

In the long run, managing all such files through web server rules (and having to always remember these rules whenever a file is added to the repo) is a big burden. HAWKI deployments could benefit from moving all files for the web server into a subdirectory within the repository. The README file could explain that only that directory has to be put into the public web tree.

An even further step, which might be beneficial for future development, could be addition of a smallish build system that copies files around to a `dist` directory or similar.

What do you think?

**Comment by Ariansdf** [comment]
Hey @nicoroeser 
Thanks for your feedback. 
We are already working on this idea. It will be included in the next main release.
Regards
