### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by StenSeegel** [HAWK-Digital-Environments/HAWKI#44]
Please add an admin panel. The basic functionality could be as follows:
- edit landing page newsfeed 
- add and remove sections/bots in the lefthand menu 
- edit chatbot system prompts for both the team and learning area 
At the moment it's not possible to do this without direct access to the server. 
With an admin panel, it would be possible for authorised users to change text and basic chatbot functionality.

**Comment by Ariansdf** [comment]
Hey @Sten
As you already know. It's coming soon in the new version.
I'm going to close the issue for now to make a little more space here.
Thank you.
