### ISSUE TITLE
Enable smooth scrolling during text generation

### ISSUE THREAD

**Issue by salzig1** [HAWK-Digital-Environments/HAWKI#51]
While the text is generated, you cant really scroll up to read the already written text.

**Comment by Ariansdf** [comment]
Hello @salzig1 
in the new version I have added an extra condition to stop auto scroll as the user is scrolling.
Please check [interface-functions](https://github.com/HAWK-Digital-Environments/HAWKI/blob/main/public/js/interface_functions.js)
I will leave this thread open for now if you needed to give us more feedback about it.
