### ISSUE TITLE
LDAP DisplayName implementation leads to empty username

### ISSUE THREAD

**Issue by ItsNotYou** [HAWK-Digital-Environments/HAWKI#75]
_First: I can submit a pull request for the change if we agree on the goal._

# Short form

The LDAP code expects the displayname in a certain format and returns empty results if the format is not fulfilled. This at least blocks the submission of feedback. I recommend an optional switch in the `.env` config file that sets default initials.

# Long form

## The problematic code
In the [LDAP part of `auth.php`](https://github.com/HAWK-Digital-Environments/HAWKI/blob/main/private/app/php/auth.php#L124), the code tries to generate username initials from the LDAP displayname field:
```php
            // Extract initials from user's display name
            $name = $info[0]["displayname"][0];
            $parts = explode(", ", $name);
            $initials = substr($parts[1], 0, 1) . substr($parts[0], 0, 1);

            // Set session variables
            $_SESSION['username'] = $initials;
```

The code expects the displayname to be in the format `Mustermann, Max`. If the displayname looks like `Max Mustermann`, the code fails and returns an empty username.

## The effect
At the very least, this means that no feedback can be sent, [as the feedback code terminates with an error message if messages and usernames are empty](https://github.com/HAWK-Digital-Environments/HAWKI/blob/6ae6684c3a09dc630e804ba993e725b5fa15d417/private/app/php/feedback_send.php#L64).

## General conditions
The expectation that the display name is formatted with a comma is not supported by the RFC.
* https://doku.tid.dfn.de/de:common_attributes#a02
* https://wiki.refeds.org/display/STAN/eduPerson+2020-01#eduPerson202001-displayName

At our institution, the displayname may have the following formats:
* Max Mustermann
* Mustermann, Max
* Max
* Prof. Dr. Max Mustermann
* Prof. Dr. Mustermann, Max
* Prof. Dr. Mustermann

## Proposed solution
We don't need the initals to work with HAWKI. For data protection reasons, we are even happy if no initials are displayed. Therefore, a switch that sets all initials to the abbreviation of the university (in our case _UP_ for _University of Potsdam_) would be practical for us. The option could be called `ldap_default_initials`.

**Comment by Ariansdf** [comment]
Hey @ItsNotYou,
sorry for the late reply, I had a long vacation in june and should now still answer a ton of emails and messages...
This part for sure a needs some modifications. We also had problems with the LDAP attribute names on different servers or very long usernames.
If you want a fast solution only for the "displayed initials", you can just override the message-icon value assignment at line 627 in interface.php with a hard coded one or read your variable from .env with an extra php block.
But please keep in mind that overriding the received information from the LDAP server and assigning a fixed value to the session username could cause some security risks. Moreover, in the upcoming commits we will be using more username dependent features (such as chat history etc.).
I'm generally planning to create more complex / elegant solutions for such matters in the version 2.0, which will allow the user to configure them as they wish. 
We'll inform you soon about the features and release dates.
Anyways, I'll be more than happy if you could also share your solution here. We can then decide how to implement it in the main code.
Thanks for your feedback and your contribution to the project.
best regards,
Arian

**Comment by ItsNotYou** [comment]
Hello @Ariansdf,

Thank you for your reply. I just added a pull request.

I understand that HAWKI may want to use the username for future cases. For security-critical functions, however, using the initials is inadequate either way. If something changes in future functions, then I trust that you will find a better solution than the current initials.

**Comment by ItsNotYou** [comment]
Hello @Ariansdf,

Have you had time to look at the Merge Request https://github.com/HAWK-Digital-Environments/HAWKI/pull/80?

**Comment by Ariansdf** [comment]
Hey @ItsNotYou sorry for the late reply I was very busy in the last weeks.
I just found some time to review and merge your pull request.
Thanks for your contribution.
Regards
