### ISSUE TITLE
Fehler in README.md bezüglich API keys?

### ISSUE THREAD

**Issue by nbluemer** [HAWK-Digital-Environments/HAWKI#95]
In Zeile 102 von README.md steht:

| GWDG_API_URL   | string  | "https://api.openai.com/v1/chat/completions" | GWDG Endpoint URL        

Offensichtlich bezieht sich diese URL aber auf OpenAI (und ist auch in Zeile 100 als OpenAI API URL angegeben).

**Comment by ItsNotYou** [comment]
Hallo @nbluemer,

die Dokumentation ist da tatsächlich fehlerhaft. In https://github.com/HAWK-Digital-Environments/HAWKI/blob/main/private/.env.example steht auch

```ini
#GWDG Ai Config
GWDG_API_URL="https://chat-ai.academiccloud.de/v1/chat/completions"
GWDG_API_KEY=""
```

Ich war so dreist und habe die Korrektur zu meinem bestehenden Pull Request #96 hinzugefügt.

**Comment by Ariansdf** [comment]
Hello @nbluemer @ItsNotYou 
It seems like I have forgotten to merge the PR in the main branch. Please Pull the main branch to apply the changes.
